
version: '3.0'
services:
  web:
    # TODO: build context, ports and redis dependency
    build: .
    depends_on:
        - redis
    ports:
        - "5000:5000"
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    # TODO: missing persistence for redis. You need to persist /data directory.

# Aby włączyć persystencję należy wykomentować poniższe linijki
#    volumes:
#        - redis-data:/data
#volumes:
#    redis-data:

