
version: '3.0'
services:
  web:
    # TODO: image, ports and redis dependency
    image: web
    depends_on:
        - redis
    ports:
        - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc3
    # TODO: persistence for redis. You need to persist /data directory.
    volumes:
        - redis-data:/data
volumes:
    redis-data:
